plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nammaoor.sevai'
    compileSdk 34

    defaultConfig {
        applicationId "com.nammaoor.sevai"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // அடிப்படை ஆப்பிற்கு வேறு எந்த ஃபைல்களும் தற்போதைக்குத் தேவையில்லை
}
